-- HOMEWORK 3.1


-- 1) FAZER UM RIGHT OUTER JOIN ENTRE AS TABELAS;
SELECT P.NOME, C.NUMERO
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  
  
 
-- 2) FAZER UM RIGHT OUTER JOIN ENTRE PESSOA E PESSOA_X_PESSOA_ENDERECO E ENDERECO_PESSOA;
SELECT *
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 


 
-- 3) FAZER UM RIGHT OUTER JOIN ENTRE TODAS AS TABELAS COMEÇANDO POR PESSOA;
SELECT *
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
 
 
 
-- 4) FAZER UM FULL OUTER JOIN ENTRE PESSOA E CONTATO;
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  

  
-- 5) FAZER UM FULL OUTER JOIN ENTRE PESSOA, PESSOA X PESSOA ENDERECO E ENDERECO PESSOA;
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 
  
  
  
-- 6) FAZER O FULL OUTER JOIN ENTRE TODAS AS TABELAS
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 
  
  

-- 7) FAZER UM EXISTS SELECIONANDO TODAS AS PESSOAS QUE TEM ENDEREÇO
SELECT P.NOME, P.ID_PESSOA
  FROM PESSOA P
 WHERE EXISTS (SELECT PXPE.ID_PESSOA
                 FROM PESSOA_X_PESSOA_ENDERECO PXPE
                WHERE PXPE.ID_PESSOA = P.ID_PESSOA)
                
 
                
-- 8) SELECIONAR ID, NOME DA TABELA PESSOA, JUNTO COM ID, LOGRADOURO DA TABELA;
SELECT P.NOME, P.ID_PESSOA, EP.ID_ENDERECO, EP.LOGRADOURO
  FROM PESSOA P
  FULL JOIN PESSOA_x_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = P.ID_ENDERECO)
 