-- HOMEWORK2

-- SELECIONAR TODOS OS PAÍSES ORDENADOS POR NOME DESCRESCENTE
SELECT * 
  FROM VEM_SER.PAIS ORDER BY NOME DESC;


--SELECIONAR LOGRADOURO E CEP. PORÉM SOMENTE OS LOGRADOUROS QUE COMECEM COM 'A' OU 'a'.
SELECT LOGRADOURO, CEP 
  FROM VEM_SER.ENDERECO 
 WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT LOGRADOURO, CEP
  FROM VEM_SER.ENDERECO
 WHERE LOGRADOURO LIKE 'A%' OR LOGRADOURO LIKE 'a%';


--SELECIONAR TODOS OS ENDEREÇOS QUE TENHAM CEP COM FINAL '0'
SELECT * 
  FROM VEM_SER.ENDERECO
 WHERE TRIM(CEP) LIKE '%0';


--SELECIONAR TODOS OS ENDEREÇOS QUE TENHAM NÚMEROS ENTRE 1 E 100;
SELECT * 
  FROM VEM_SER.ENDERECO 
 WHERE NUMERO BETWEEN 1 AND 100; 


--SELECIONAR TODOS OS ENDEREÇOS QUE COMECEM POR 'RUA' E ORDENAR PELO CEP DECRESCENTE
SELECT *
  FROM VEM_SER.ENDERECO
 WHERE UPPER(LOGRADOURO) LIKE 'RUA%' ORDER BY CEP DESC; 
 

--SELECIONAR A QUANTIDADE DE ENDEREÇOS CADASTRADOS NA TABELA
SELECT COUNT(ID_ENDERECO) 
  FROM VEM_SER.ENDERECO;


--SELECIONAR A QUANTIDADE DE ENDEREÇOS CADASTRADOS AGRUPADOS PELO ID DA CIDADE
SELECT COUNT(ID_ENDERECO)
  FROM VEM_SER.ENDERECO
 GROUP BY ID_CIDADE;
