-- HOMEWORK 3.1

--- RIGHT OUTER JOIN
-- PESSOA E CONTATO
SELECT P.NOME, C.NUMERO
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  
  
-- PESSOA, PESSOA_X_PESSOA_ENDERECO E ENDERECO_PESSOA
SELECT *
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 


-- TODAS AS TABELAS COMECANDO POR PESSOA
SELECT *
  FROM VEM_SER.PESSOA P
 RIGHT OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
 
 
--- FULL OUTER JOIN
-- PESSOA E CONTATO
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  

-- PESSOA, PESSOA_X_PESSOA_ENDERECO E ENDERECO_PESSOA
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 
  
  
-- TODAS AS TABELAS COMECANDO POR PESSOA
SELECT *
  FROM VEM_SER.PESSOA P
  FULL OUTER JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO) 
  

-- EXISTS PESSOAS COM ENDERECO
SELECT P.NOME, P.ID_PESSOA
  FROM PESSOA P
 WHERE EXISTS (SELECT PXPE.ID_PESSOA
                 FROM PESSOA_X_PESSOA_ENDERECO PXPE
                WHERE PXPE.ID_PESSOA = P.ID_PESSOA)
                
 
                
-- ID, NOME DA TABELA PESSOA COM ID, LOGRADOURO DA TABELA ENDERECO
SELECT P.NOME, P.ID_PESSOA, EP.ID_ENDERECO, EP.LOGRADOURO
  FROM PESSOA P
 INNER JOIN ENDERECO_PESSOA EP ON (P.ID_PESSOA = EP.ID_ENDERECO)
 WHERE EXISTS (SELECT PXPE.ID_PESSOA
                 FROM PESSOA_X_PESSOA_ENDERECO PXPE
                WHERE PXPE.ID_PESSOA = P.ID_PESSOA)
 