CREATE TABLE VEM_SER.ESTUDANTE(
	id_estudante NUMBER NOT NULL,
	nome VARCHAR(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR(1),
	PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Alyson', '03/09/1991', 1000, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Natalia', '11/10/1989', 1002, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Campos', '27/06/1995', 1003, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Inailde', '15/01/1986', 1004, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Agadi', '08/07/1996', 1005, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Carlos', '11/09/1970', 1006, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Lourenço', '18/03/1964', 1007, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Valentin', '09/05/1996', 1008, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Lula', '13/04/1990', 1009, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Alain', '06/07/1992', 1010, 'S');

SELECT * FROM ESTUDANTE;

